export const dashboardMockData = {
  kpis: {
    activeVehicles: 53,
    availableVehicles: 42,
    vehiclesInMaintenance: 5,
    activeTrips: 18,
    pendingTrips: 9,
    driversOnDuty: 26,
    fleetUtilizationPct: 81,
  },
  recentTrips: [
    {
      tripCode: "TR001",
      vehicleLabel: "KA-01-AB-1234",
      driverLabel: "Aarav Shah",
      status: "ON_TRIP",
      eta: "45 min",
      updated: "2m ago",
      vehicleType: "TRUCK",
      region: "North",
    },
    {
      tripCode: "TR002",
      vehicleLabel: "KA-03-CD-5678",
      driverLabel: "Rohan Mehta",
      status: "COMPLETED",
      eta: "—",
      updated: "15m ago",
      vehicleType: "VAN",
      region: "South",
    },
    {
      tripCode: "TR003",
      vehicleLabel: "MH-12-EF-9012",
      driverLabel: "Vikram Joshi",
      status: "DISPATCHED",
      eta: "1h 10m",
      updated: "20m ago",
      vehicleType: "TRUCK",
      region: "West",
    },
    {
      tripCode: "TR004",
      vehicleLabel: "DL-1L-GH-3456",
      driverLabel: "Neeraj Kapoor",
      status: "IN_SHOP",
      eta: "—",
      updated: "1h ago",
      vehicleType: "MINI",
      region: "East",
    },
    {
      tripCode: "TR005",
      vehicleLabel: "GJ-05-IJ-7890",
      driverLabel: "Sandeep Patel",
      status: "RETIRED",
      eta: "—",
      updated: "2h ago",
      vehicleType: "VAN",
      region: "West",
    },
  ],
  vehicleStatusBreakdown: {
    available: 42,
    onTrip: 18,
    inShop: 5,
    retired: 9,
    onStandby: 26,
  },
  dateRange: "Apr 20 - Apr 27, 2025",
};

export type DashboardData = typeof dashboardMockData;
