export const dashboardMockData = {
  kpis: {
    activeVehicles: 24,
    availableVehicles: 12,
    vehiclesInMaintenance: 3,
    activeTrips: 9,
    pendingTrips: 5,
    driversOnDuty: 18,
    fleetUtilizationPct: 50,
  },
  recentTrips: [
    {
      tripCode: "TR001",
      vehicleLabel: "KA-01-AB-1234 (Truck)",
      driverLabel: "Rajesh Kumar",
      status: "DISPATCHED",
      eta: "2h 30m",
      vehicleType: "TRUCK",
      region: "North",
    },
    {
      tripCode: "TR002",
      vehicleLabel: "KA-02-CD-5678 (Van)",
      driverLabel: "Amit Singh",
      status: "COMPLETED",
      eta: "Arrived",
      vehicleType: "VAN",
      region: "South",
    },
    {
      tripCode: "TR003",
      vehicleLabel: "KA-03-EF-9012 (Mini)",
      driverLabel: "Priya Sharma",
      status: "DISPATCHED",
      eta: "1h 15m",
      vehicleType: "MINI",
      region: "East",
    },
    {
      tripCode: "TR004",
      vehicleLabel: "KA-04-GH-3456 (Truck)",
      driverLabel: "Vikram Reddy",
      status: "DRAFT",
      eta: "Not started",
      vehicleType: "TRUCK",
      region: "West",
    },
    {
      tripCode: "TR005",
      vehicleLabel: "KA-05-IJ-7890 (Van)",
      driverLabel: "Sunita Patel",
      status: "DISPATCHED",
      eta: "3h 45m",
      vehicleType: "VAN",
      region: "North",
    },
    {
      tripCode: "TR006",
      vehicleLabel: "KA-06-KL-2345 (Truck)",
      driverLabel: "Ravi Verma",
      status: "CANCELLED",
      eta: "Cancelled",
      vehicleType: "TRUCK",
      region: "South",
    },
    {
      tripCode: "TR007",
      vehicleLabel: "KA-07-MN-6789 (Mini)",
      driverLabel: "Deepak Joshi",
      status: "COMPLETED",
      eta: "Arrived",
      vehicleType: "MINI",
      region: "East",
    },
    {
      tripCode: "TR008",
      vehicleLabel: "KA-08-OP-0123 (Other)",
      driverLabel: "Anjali Mehta",
      status: "DRAFT",
      eta: "Not started",
      vehicleType: "OTHER",
      region: "West",
    },
  ],
  vehicleStatusBreakdown: {
    available: 12,
    onTrip: 9,
    inShop: 3,
    retired: 2,
  },
};

export type DashboardData = typeof dashboardMockData;
